version: "3.8"

services:
  ms-guias-productor:
    image: ${DOCKERHUB_USERNAME}/ms-guias-productor:latest
    container_name: ms-guias-productor
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}

      AZURE_TENANT_NAME: ${AZURE_TENANT_NAME:-demoCloudNative}
      AZURE_USER_FLOW: ${AZURE_USER_FLOW:-B2C_1_acceso}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID:-}
    networks:
      - guias-red
    restart: unless-stopped

  ms-guias-consumidor:
    image: ${DOCKERHUB_USERNAME}/ms-guias-consumidor:latest
    container_name: ms-guias-consumidor
    ports:
      - "8081:8081"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest

      ORACLE_DB_URL: ${ORACLE_DB_URL:-}
      ORACLE_DB_USER: ${ORACLE_DB_USER:-}
      ORACLE_DB_PASS: ${ORACLE_DB_PASS:-}

      AZURE_TENANT_NAME: ${AZURE_TENANT_NAME:-demoCloudNative}
      AZURE_USER_FLOW: ${AZURE_USER_FLOW:-B2C_1_acceso}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID:-}
    networks:
      - guias-red
    restart: unless-stopped

networks:
  guias-red:
    name: guias-red
    external: true
