spring.datasource.url=${ORACLE_DB_URL:jdbc:oracle:thin:@//CAMBIAR_HOST:1521/CAMBIAR_SERVICE_NAME}
spring.datasource.username=${ORACLE_DB_USER:CAMBIAR_USUARIO}
spring.datasource.password=${ORACLE_DB_PASS:CAMBIAR_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
